// Generated by CoffeeScript 1.11.1
var dv, tesseractInstance;

dv = require('dv');

tesseractInstance = null;

module.exports = function(image) {
  if (tesseractInstance == null) {
    tesseractInstance = new dv.Tesseract();
  }
  tesseractInstance.image = image;
  return tesseractInstance.thresholdImage();
};
