// Generated by CoffeeScript 1.11.1
var dv;

dv = require('dv');

module.exports = function(image) {
  var binarizedImage, grayImage, skew;
  grayImage = image.toGray();
  binarizedImage = grayImage.otsuAdaptiveThreshold(400, 400, 0, 0, 0.1).image;
  skew = binarizedImage.findSkew().angle;
  if (Math.abs(skew) < 0.15) {
    skew = 0;
  }
  if (skew) {
    return image.rotate(skew);
  } else {
    return new dv.Image(image);
  }
};
