// Generated by CoffeeScript 1.11.1
module.exports = function(image, fontWidth, fontHeight) {
  var backgroundMask, foreground;
  backgroundMask = image.toGray().close(fontWidth, fontHeight).convolve(fontWidth * 1.33, fontHeight * 1.33).invert();
  backgroundMask = backgroundMask.add(backgroundMask);
  foreground = image.toColor().add(backgroundMask.toColor());
  return foreground;
};
