// Generated by CoffeeScript 1.11.1
module.exports.unpack = function(object, path) {
  var i, item, len, ref, tail;
  tail = object;
  ref = path.split('.');
  for (i = 0, len = ref.length; i < len; i++) {
    item = ref[i];
    if (tail[item] == null) {
      tail[item] = {};
    }
    tail = tail[item];
  }
  return tail;
};

module.exports.validate = function(field, value, defaultResult) {
  if (field.fieldValidator != null) {
    return Boolean(field.fieldValidator(value));
  } else {
    return defaultResult;
  }
};
